import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Business Valuation Explained | Guide to Valuing a Business – Acquity",
  description:
    "Learn the fundamentals of business valuation, key metrics, and how to determine fair market value.",
};

export default function BusinessValuationPage() {
  return (
    <main className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-50 to-blue-100 border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-24">
          <Link
            href="/resources"
            className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-700 mb-6 font-medium"
          >
            <span className="material-symbols-outlined text-[20px]">
              arrow_back
            </span>
            Back to Resources
          </Link>
          <h1 className="text-4xl md:text-5xl font-black text-gray-900 mb-6">
            Business Valuation Explained
          </h1>
          <p className="text-xl text-gray-600">
            Learn the fundamentals of business valuation, key metrics, and how
            to determine fair market value.
          </p>
        </div>
      </section>

      {/* Content Section */}
      <article className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="prose prose-lg max-w-none">
          <h2>What is Business Valuation?</h2>
          <p>
            Business valuation is the process of determining the economic value
            of a company. It's essential for buyers, sellers, investors, and
            business owners to understand how much a business is truly worth.
          </p>

          <h2>Common Valuation Methods</h2>

          <h3>1. Asset-Based Valuation</h3>
          <p>
            This method calculates the net value of a business's assets minus
            its liabilities:
          </p>
          <ul>
            <li>
              <strong>Book Value:</strong> Assets minus liabilities based on
              balance sheet
            </li>
            <li>
              <strong>Liquidation Value:</strong> What assets would fetch if
              sold quickly
            </li>
            <li>
              <strong>Replacement Value:</strong> Cost to replace all assets
            </li>
          </ul>

          <h3>2. Earnings-Based Valuation</h3>
          <p>
            These methods focus on the company's ability to generate profit:
          </p>
          <ul>
            <li>
              <strong>EBITDA Multiple:</strong> Most common for small to
              mid-sized businesses (typically 2-5x EBITDA)
            </li>
            <li>
              <strong>SDE Multiple:</strong> Seller's Discretionary Earnings
              (owner's salary + profits + discretionary expenses)
            </li>
            <li>
              <strong>P/E Ratio:</strong> Price to Earnings ratio for larger
              companies
            </li>
          </ul>

          <h3>3. Market-Based Valuation</h3>
          <p>Compares the business to similar companies that have been sold:</p>
          <ul>
            <li>Recent sales of comparable businesses</li>
            <li>Industry-specific multiples</li>
            <li>Market trends and conditions</li>
          </ul>

          <h3>4. Discounted Cash Flow (DCF)</h3>
          <p>Projects future cash flows and discounts them to present value:</p>
          <ul>
            <li>
              Most suitable for established businesses with predictable cash
              flow
            </li>
            <li>Requires detailed financial projections</li>
            <li>Sensitive to discount rate assumptions</li>
          </ul>

          <h2>Key Financial Metrics</h2>

          <h3>Revenue</h3>
          <p>
            Total income generated from business operations. Look for consistent
            growth and stable revenue streams.
          </p>

          <h3>EBITDA</h3>
          <p>
            Earnings Before Interest, Taxes, Depreciation, and Amortization.
            Shows operational profitability without financing and accounting
            decisions.
          </p>

          <h3>Profit Margins</h3>
          <p>
            Net profit divided by revenue. Higher margins indicate better
            efficiency and pricing power.
          </p>

          <h3>Cash Flow</h3>
          <p>
            Actual cash generated by the business. More important than
            accounting profit for valuation.
          </p>

          <h2>Factors Affecting Valuation</h2>
          <ul>
            <li>
              <strong>Industry:</strong> Different industries command different
              multiples
            </li>
            <li>
              <strong>Size:</strong> Larger businesses typically have higher
              multiples
            </li>
            <li>
              <strong>Growth Rate:</strong> Fast-growing businesses are valued
              higher
            </li>
            <li>
              <strong>Customer Concentration:</strong> Diversified customer base
              increases value
            </li>
            <li>
              <strong>Owner Dependency:</strong> Businesses less reliant on
              owner are worth more
            </li>
            <li>
              <strong>Market Conditions:</strong> Economic climate affects buyer
              demand
            </li>
            <li>
              <strong>Competition:</strong> Unique positioning increases value
            </li>
            <li>
              <strong>Recurring Revenue:</strong> Subscription models command
              premium valuations
            </li>
          </ul>

          <h2>Typical Valuation Multiples by Industry</h2>
          <ul>
            <li>
              <strong>Technology/SaaS:</strong> 3-10x revenue (or 10-20x EBITDA)
            </li>
            <li>
              <strong>E-commerce:</strong> 2-4x SDE
            </li>
            <li>
              <strong>Manufacturing:</strong> 3-5x EBITDA
            </li>
            <li>
              <strong>Service Businesses:</strong> 2-4x SDE
            </li>
            <li>
              <strong>Retail:</strong> 1.5-3x SDE
            </li>
            <li>
              <strong>Restaurants:</strong> 1.5-3x SDE
            </li>
          </ul>

          <h2>Red Flags in Business Valuation</h2>
          <ul>
            <li>Declining revenue or profit trends</li>
            <li>Heavy reliance on one or few customers</li>
            <li>Owner-dependent operations</li>
            <li>Unverified or inconsistent financial records</li>
            <li>High employee turnover</li>
            <li>Legal or regulatory issues</li>
            <li>Outdated technology or equipment</li>
            <li>Pending lawsuits or liabilities</li>
          </ul>

          <h2>Getting a Professional Valuation</h2>
          <p>Consider hiring a business valuation expert for:</p>
          <ul>
            <li>Complex businesses with multiple revenue streams</li>
            <li>High-value transactions</li>
            <li>Legal requirements (divorce, estate planning)</li>
            <li>Negotiations with serious buyers</li>
            <li>SBA loan applications</li>
          </ul>
        </div>

        {/* CTA Section */}
        <div className="mt-16 p-8 bg-blue-50 rounded-lg border border-blue-200">
          <h3 className="text-2xl font-bold text-gray-900 mb-4">
            Explore Valued Businesses
          </h3>
          <p className="text-gray-600 mb-6">
            All listings on Acquity include key financial metrics to help you
            assess value and make informed decisions.
          </p>
          <Link
            href="/businesses-for-sale"
            className="inline-flex items-center gap-2 bg-blue-600 text-white px-6 py-3 rounded-lg font-bold hover:bg-blue-700 transition-colors"
          >
            Browse Businesses for Sale
            <span className="material-symbols-outlined text-[20px]">
              arrow_forward
            </span>
          </Link>
        </div>
      </article>
    </main>
  );
}
