/**
 * Launch Mode Configuration
 * Control pre-launch waitlist and mock listing display
 */

export const LAUNCH_MODE = true; // Set to false to disable waitlist banner and show real listings

/**
 * Mock Listing Data for Launch Preview
 * Blurred placeholder listings shown when LAUNCH_MODE is true
 */
export const MOCK_BUSINESS_LISTINGS = [
  {
    id: "mock-1",
    slug: "restaurant-chain-dubai",
    type: "business_sale" as const,
    title: "Established Restaurant Chain",
    location: "Dubai, UAE",
    country: "UAE",
    category: "Food & Beverage",
    subCategory: "Full Sale",
    image: "/placeholder-business.jpg",
    badge: "EXCLUSIVE",
    plan: "premium" as const,
    price: 2500000,
    revenue: 1800000,
    ebitda: 450000,
  },
  {
    id: "mock-2",
    slug: "tech-startup-kenya",
    type: "business_sale" as const,
    title: "SaaS Technology Company",
    location: "Nairobi, Kenya",
    country: "Kenya",
    category: "Technology",
    subCategory: "Full Sale",
    image: "/placeholder-business.jpg",
    badge: "VERIFIED",
    plan: "standard" as const,
    price: 850000,
    revenue: 420000,
    ebitda: 180000,
  },
  {
    id: "mock-3",
    slug: "ecommerce-brand-egypt",
    type: "business_sale" as const,
    title: "E-Commerce Fashion Brand",
    location: "Cairo, Egypt",
    country: "Egypt",
    category: "E-Commerce",
    subCategory: "Full Sale",
    image: "/placeholder-business.jpg",
    plan: "basic" as const,
    price: 320000,
    revenue: 280000,
    ebitda: 65000,
  },
  {
    id: "mock-4",
    slug: "logistics-company-ksa",
    type: "business_sale" as const,
    title: "Regional Logistics Provider",
    location: "Riyadh, Saudi Arabia",
    country: "Saudi Arabia",
    category: "Logistics",
    subCategory: "Full Sale",
    image: "/placeholder-business.jpg",
    badge: "EXCLUSIVE",
    plan: "premium" as const,
    price: 3200000,
    revenue: 2100000,
    ebitda: 580000,
  },
  {
    id: "mock-5",
    slug: "manufacturing-morocco",
    type: "business_sale" as const,
    title: "Manufacturing Facility",
    location: "Casablanca, Morocco",
    country: "Morocco",
    category: "Manufacturing",
    subCategory: "Full Sale",
    image: "/placeholder-business.jpg",
    plan: "standard" as const,
    price: 1750000,
    revenue: 1200000,
    ebitda: 340000,
  },
  {
    id: "mock-6",
    slug: "real-estate-agency-qatar",
    type: "business_sale" as const,
    title: "Real Estate Agency",
    location: "Doha, Qatar",
    country: "Qatar",
    category: "Real Estate",
    subCategory: "Full Sale",
    image: "/placeholder-business.jpg",
    badge: "VERIFIED",
    plan: "premium" as const,
    price: 920000,
    revenue: 680000,
    ebitda: 210000,
  },
];

export const MOCK_FRANCHISE_LISTINGS = [
  {
    id: "mock-f1",
    slug: "coffee-franchise-uae",
    type: "franchise_sale" as const,
    title: "Premium Coffee Franchise",
    location: "Abu Dhabi, UAE",
    country: "UAE",
    category: "Food & Beverage",
    subCategory: "Franchise",
    image: "/placeholder-franchise.jpg",
    badge: "EXCLUSIVE",
    plan: "premium" as const,
    price: "150000",
    revenue: "420000",
    profit: "95000",
  },
  {
    id: "mock-f2",
    slug: "fitness-franchise-lebanon",
    type: "franchise_sale" as const,
    title: "Fitness Studio Franchise",
    location: "Beirut, Lebanon",
    country: "Lebanon",
    category: "Health & Fitness",
    subCategory: "Franchise",
    image: "/placeholder-franchise.jpg",
    plan: "standard" as const,
    price: "85000",
    revenue: "180000",
    profit: "42000",
  },
  {
    id: "mock-f3",
    slug: "tutoring-franchise-jordan",
    type: "franchise_sale" as const,
    title: "Education & Tutoring Franchise",
    location: "Amman, Jordan",
    country: "Jordan",
    category: "Education",
    subCategory: "Franchise",
    image: "/placeholder-franchise.jpg",
    badge: "VERIFIED",
    plan: "basic" as const,
    price: "45000",
    revenue: "120000",
    profit: "28000",
  },
  {
    id: "mock-f4",
    slug: "retail-franchise-kuwait",
    type: "franchise_sale" as const,
    title: "Retail Convenience Store",
    location: "Kuwait City, Kuwait",
    country: "Kuwait",
    category: "Retail",
    subCategory: "Franchise",
    image: "/placeholder-franchise.jpg",
    plan: "premium" as const,
    price: "110000",
    revenue: "320000",
    profit: "68000",
  },
  {
    id: "mock-f5",
    slug: "car-wash-franchise-oman",
    type: "franchise_sale" as const,
    title: "Auto Care Franchise",
    location: "Muscat, Oman",
    country: "Oman",
    category: "Automotive",
    subCategory: "Franchise",
    image: "/placeholder-franchise.jpg",
    badge: "EXCLUSIVE",
    plan: "standard" as const,
    price: "72000",
    revenue: "195000",
    profit: "48000",
  },
  {
    id: "mock-f6",
    slug: "pet-care-franchise-bahrain",
    type: "franchise_sale" as const,
    title: "Pet Care Services Franchise",
    location: "Manama, Bahrain",
    country: "Bahrain",
    category: "Services",
    subCategory: "Franchise",
    image: "/placeholder-franchise.jpg",
    plan: "basic" as const,
    price: "38000",
    revenue: "95000",
    profit: "22000",
  },
];

export const MOCK_INVESTMENT_LISTINGS = [
  {
    id: "mock-i1",
    slug: "fintech-startup-nigeria",
    type: "investment_opportunity" as const,
    title: "Fintech Payment Platform",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    category: "Technology",
    subCategory: "Investment",
    image: "/placeholder-investment.jpg",
    badge: "EXCLUSIVE",
    plan: "premium" as const,
    price: "500000",
    revenue: "280000",
    equity: "15",
  },
  {
    id: "mock-i2",
    slug: "renewable-energy-morocco",
    type: "investment_opportunity" as const,
    title: "Solar Energy Project",
    location: "Rabat, Morocco",
    country: "Morocco",
    category: "Energy",
    subCategory: "Investment",
    image: "/placeholder-investment.jpg",
    badge: "VERIFIED",
    plan: "premium" as const,
    price: "1200000",
    revenue: "450000",
    equity: "20",
  },
  {
    id: "mock-i3",
    slug: "healthtech-startup-south-africa",
    type: "investment_opportunity" as const,
    title: "HealthTech Mobile App",
    location: "Cape Town, South Africa",
    country: "South Africa",
    category: "Healthcare",
    subCategory: "Investment",
    image: "/placeholder-investment.jpg",
    plan: "standard" as const,
    price: "350000",
    revenue: "120000",
    equity: "12",
  },
  {
    id: "mock-i4",
    slug: "agritech-startup-ghana",
    type: "investment_opportunity" as const,
    title: "AgriTech Supply Chain",
    location: "Accra, Ghana",
    country: "Ghana",
    category: "Agriculture",
    subCategory: "Investment",
    image: "/placeholder-investment.jpg",
    badge: "EXCLUSIVE",
    plan: "standard" as const,
    price: "280000",
    revenue: "95000",
    equity: "18",
  },
  {
    id: "mock-i5",
    slug: "ecommerce-platform-pakistan",
    type: "investment_opportunity" as const,
    title: "B2B E-Commerce Platform",
    location: "Karachi, Pakistan",
    country: "Pakistan",
    category: "E-Commerce",
    subCategory: "Investment",
    image: "/placeholder-investment.jpg",
    plan: "premium" as const,
    price: "650000",
    revenue: "380000",
    equity: "22",
  },
  {
    id: "mock-i6",
    slug: "edtech-startup-india",
    type: "investment_opportunity" as const,
    title: "EdTech Learning Platform",
    location: "Mumbai, India",
    country: "India",
    category: "Education",
    subCategory: "Investment",
    image: "/placeholder-investment.jpg",
    badge: "VERIFIED",
    plan: "basic" as const,
    price: "420000",
    revenue: "210000",
    equity: "16",
  },
];
